apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  rules:
    - host: bay.com
      http:
        paths:
          # auth service
          - path: /api/users/?(.*)
            backend:
              serviceName: auth-srv
              servicePort: 3000
          # tickets service
          - path: /api/tickets/?(.*)
            backend:
              serviceName: tickets-srv
              servicePort: 3000
          # client next.js ssr app
          - path: /?(.*)
            backend:
              serviceName: client-srv
              servicePort: 3000
